In [3]:
import torch as tr
import numpy as np

In [4]:
tr.__version__

'1.5.0'

In [10]:
x = [1,2,3]
ar = np.array(x)
print(ar)
print(ar.shape)

[1 2 3]
(3,)


In [11]:
tensor = tr.tensor(x)
print(tensor)
print(tensor.shape)

tensor([1, 2, 3])
torch.Size([3])


In [14]:
print(ar.mean())
print(tensor.float().mean())

2.0
tensor(2.)


In [16]:
tensor = tr.randn((2,2))
tensor

tensor([[-0.4550,  0.2210],
        [ 0.8113,  0.3034]])

In [17]:
# Matrix Multiplication
tensor@tensor

tensor([[ 0.3863, -0.0335],
        [-0.1230,  0.2714]])

In [18]:
tensor.T

tensor([[-0.4550,  0.8113],
        [ 0.2210,  0.3034]])

In [20]:
tensor = tr.tensor([1,1,23])
tensor.view((3,1))

tensor([[ 1],
        [ 1],
        [23]])

# Linear Regression using PyTorch

In [22]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
sns.set_style('dark')

In [23]:
X = pd.read_csv("")

FileNotFoundError: [Errno 2] File /Users/jgoel/Desktop/Data Science Self/LinearRegression/Linear_X_Train.csv does not exist: '/Users/jgoel/Desktop/Data Science Self/LinearRegression/Linear_X_Train.csv'